cityTimeZones = [
    ["Accra", "Ghana", "Africa/Accra"],
    ["Addis Ababa", "Ethiopia", "Africa/Addis_Ababa"],
    ["Adelaide", "Australia", "Australia/Adelaide"],
    ["Algiers", "Algeria", "Africa/Algiers"],
    ["Almaty", "Kazakstan", "Asia/Almaty"],
    ["Amman", "Jordan", "Asia/Amman"],
    ["Amsterdam", "Netherlands", "Europe/Amsterdam"],
    ["Anadyr", "Russia", "Asia/Anadyr"],
    ["Anchorage", "USA", "America/Anchorage"],
    ["Ankara", "Turkey", "Europe/Istanbul"],
    ["Antananarivo", "Madagascar", "Indian/Antananarivo"],
    ["Asuncion", "Paraguay", "America/Asuncion"],
    ["Athens", "Greece", "Europe/Athens"],
    ["Atlanta", "USA", "America/New_York"],
    ["Auckland", "New-Zealand", "Pacific/Auckland"],
    ["Baghdad", "Iraq", "Asia/Baghdad"],
    ["Bangalore", "India", "Asia/Kolkata"],
    ["Bangkok", "Thailand", "Asia/Bangkok"],
    ["Barcelona", "Spain", "Europe/Madrid"],
    ["Beijing", "China", "Asia/Shanghai"],
    ["Beirut", "Lebanon", "Asia/Beirut"],
    ["Belgrade", "Serbia", "Europe/Belgrade"],
    ["Berlin", "Germany", "Europe/Berlin"],
    ["Bogota", "Colombia", "America/Bogota"],
    ["Boston", "USA", "America/New_York"],
    ["Brasilia", "Brazil", "America/Sao_Paulo"],
    ["Brisbane", "Australia", "Australia/Brisbane"],
    ["Brussels", "Belgium", "Europe/Brussels"],
    ["Bucharest", "Romania", "Europe/Bucharest"],
    ["Budapest", "Hungary", "Europe/Budapest"],
    ["Buenos Aires", "Argentina", "America/Argentina/Buenos_Aires"],
    ["Cairo", "Egypt", "Africa/Cairo"],
    ["Calgary", "Canada", "America/Edmonton"],
    ["Canberra", "Australia", "Australia/Sydney"],
    ["Cape Town", "South-Africa", "Africa/Johannesburg"],
    ["Caracas", "Venezuela", "America/Caracas"],
    ["Casablanca", "Morocco", "Africa/Casablanca"],
    ["Chicago", "USA", "America/Chicago"],
    ["Copenhagen", "Denmark", "Europe/Copenhagen"],
    ["Dallas", "USA", "America/Winnipeg"],
    ["Dar es Salaam", "Tanzania", "Africa/Dar_es_Salaam"],
    ["Darwin", "Australia", "Australia/Darwin"],
    ["Denver", "USA", "America/Denver"],
    ["Detroit", "USA", "America/Detroit"],
    ["Dhaka", "Bangladesh", "Asia/Dhaka"],
    ["Doha", "Qatar", "Asia/Qatar"],
    ["Dubai", "United-Arab-Emirates", "Asia/Dubai"],
    ["Dublin", "Ireland", "Europe/Dublin"],
    ["Edmonton", "Canada", "America/Edmonton"],
    ["Frankfurt", "Germany", "Europe/Berlin"],
    ["Guatemala City", "Guatemala", "America/Guatemala"],
    ["Halifax", "Canada", "America/Halifax"],
    ["Hanoi", "Vietnam", "Asia/Ho_Chi_Minh"],
    ["Harare", "Zimbabwe", "Africa/Harare"],
    ["Havana", "Cuba", "America/Havana"],
    ["Helsinki", "Finland", "Europe/Helsinki"],
    ["Hong Kong", "Hong-Kong", "Asia/Hong_Kong"],
    ["Honolulu", "USA", "Pacific/Honolulu"],
    ["Houston", "USA", "America/Chicago"],
    ["Indianapolis", "USA", "America/Indiana/Indianapolis"],
    ["Islamabad", "Pakistan", "Asia/Karachi"],
    ["Istanbul", "Turkey", "Europe/Istanbul"],
    ["Jakarta", "Indonesia", "Asia/Jakarta"],
    ["Jerusalem", "Israel", "Asia/Jerusalem"],
    ["Johannesburg", "South-Africa", "Africa/Johannesburg"],
    ["Kabul", "Afghanistan", "Asia/Kabul"],
    ["Karachi", "Pakistan", "Asia/Karachi"],
    ["Kathmandu", "Nepal", "Asia/Kathmandu"],
    ["Khartoum", "Sudan", "Africa/Khartoum"],
    ["Kingston", "Jamaica", "America/Jamaica"],
    ["Kinshasa", "Congo-Demrep", "Africa/Kinshasa"],
    ["Kiritimati", "Kiribati", "Pacific/Kiritimati"],
    ["Kolkata", "India", "Asia/Kolkata"],
    ["Kuala Lumpur", "Malaysia", "Asia/Kuala_Lumpur"],
    ["Kuwait City", "Kuwait", "Asia/Kuwait"],
    ["Kyiv", "Ukraine", "Europe/Kiev"],
    ["La Paz", "Bolivia", "America/La_Paz"],
    ["Lagos", "Nigeria", "Africa/Lagos"],
    ["Lahore", "Pakistan", "Asia/Karachi"],
    ["Las Vegas", "USA", "America/Los_Angeles"],
    ["Lima", "Peru", "America/Lima"],
    ["Lisbon", "Portugal", "Europe/Lisbon"],
    ["London", "Uk", "Europe/London"],
    ["Los Angeles", "USA", "America/Los_Angeles"],
    ["Madrid", "Spain", "Europe/Madrid"],
    ["Managua", "Nicaragua", "America/Managua"],
    ["Manila", "Philippines", "Asia/Manila"],
    ["Melbourne", "Australia", "Australia/Melbourne"],
    ["Mexico City", "Mexico", "America/Mexico_City"],
    ["Miami", "USA", "America/New_York"],
    ["Minneapolis", "USA", "America/Chicago"],
    ["Minsk", "Belarus", "Europe/Minsk"],
    ["Montevideo", "Uruguay", "America/Montevideo"],
    ["Montréal", "Canada", "America/Toronto"],
    ["Moscow", "Russia", "Europe/Moscow"],
    ["Mumbai", "India", "Asia/Kolkata"],
    ["Nairobi", "Kenya", "Africa/Nairobi"],
    ["Nassau", "Bahamas", "America/Nassau"],
    ["New Delhi", "India", "Asia/Kolkata"],
    ["New Orleans", "USA", "America/Chicago"],
    ["New York", "USA", "America/New_York"],
    ["Oslo", "Norway", "Europe/Oslo"],
    ["Ottawa", "Canada", "America/Toronto"],
    ["Paris", "France", "Europe/Paris"],
    ["Perth", "Australia", "Australia/Perth"],
    ["Philadelphia", "USA", "America/New_York"],
    ["Phoenix", "USA", "America/Phoenix"],
    ["Prague", "Czech-Republic", "Europe/Prague"],
    ["Reykjavik", "Iceland", "Atlantic/Reykjavik"],
    ["Rio de Janeiro", "Brazil", "America/Sao_Paulo"],
    ["Riyadh", "Saudi-Arabia", "Asia/Riyadh"],
    ["Rome", "Italy", "Europe/Rome"],
    ["Salt Lake City", "USA", "America/Denver"],
    ["San Francisco", "USA", "America/Los_Angeles"],
    ["San Juan", "Puerto-Rico", "America/Argentina/San_Juan"],
    ["San Salvador", "El-Salvador", "America/El_Salvador"],
    ["Santiago", "Chile", "America/Santiago"],
    ["Santo Domingo", "Dominican-Republic", "America/Santo_Domingo"],
    ["Seattle", "USA", "America/Los_Angeles"],
    ["Seoul", "South-Korea", "Asia/Seoul"],
    ["Shanghai", "China", "Asia/Shanghai"],
    ["Singapore", "Singapore", "Asia/Singapore"],
    ["Sofia", "Bulgaria", "Europe/Sofia"],
    ["St. John's", "Canada", "America/St_Johns"],
    ["Stockholm", "Sweden", "Europe/Stockholm"],
    ["Suva", "Fiji", "Pacific/Fiji"],
    ["Sydney", "Australia", "Australia/Sydney"],
    ["São Paulo", "Brazil", "America/Sao_Paulo"],
    ["Taipei", "Taiwan", "Asia/Taipei"],
    ["Tallinn", "Estonia", "Europe/Tallinn"],
    ["Tashkent", "Uzbekistan", "Asia/Tashkent"],
    ["Tegucigalpa", "Honduras", "America/Tegucigalpa"],
    ["Tehran", "Iran", "Asia/Tehran"],
    ["Tokyo", "Japan", "Asia/Tokyo"],
    ["Toronto", "Canada", "America/Toronto"],
    ["Vancouver", "Canada", "America/Vancouver"],
    ["Vienna", "Austria", "Europe/Vienna"],
    ["Warsaw", "Poland", "Europe/Warsaw"],
    ["Washington DC", "USA", "America/New_York"],
    ["Winnipeg", "Canada", "America/Winnipeg"],
    ["Yangon", "Myanmar", "Asia/Yangon"],
    ["Zagreb", "Croatia", "Europe/Zagreb"],
    ["Zürich", "Switzerland", "Europe/Zurich"]
];
