cityTimeZones = [
    [null, "Afghanistan", "Asia/Kabul"],
    [null, "Algeria", "Africa/Algiers"],
    [null, "Argentina", "America/Argentina/Buenos_Aires"],
    [null, "Austria", "Europe/Vienna"],
    [null, "Bahamas", "America/Nassau"],
    [null, "Bangladesh", "Asia/Dhaka"],
    [null, "Belarus", "Europe/Minsk"],
    [null, "Belgium", "Europe/Brussels"],
    [null, "Bolivia", "America/La_Paz"],
    [null, "Bulgaria", "Europe/Sofia"],
    [null, "Chile", "America/Santiago"],
    [null, "China", "Asia/Shanghai"],
    [null, "Colombia", "America/Bogota"],
    [null, "Congo, DRC", "Africa/Kinshasa"],
    [null, "Croatia", "Europe/Zagreb"],
    [null, "Czech Republic", "Europe/Prague"],
    [null, "Denmark", "Europe/Copenhagen"],
    [null, "Dominican Republic", "America/Santo_Domingo"],
    [null, "Egypt", "Africa/Cairo"],
    [null, "El Salvador", "America/El_Salvador"],
    [null, "Estonia", "Europe/Tallinn"],
    [null, "Ethiopia", "Africa/Addis_Ababa"],
    [null, "Fiji", "Pacific/Fiji"],
    [null, "Finland", "Europe/Helsinki"],
    [null, "France", "Europe/Paris"],
    [null, "Germany", "Europe/Berlin"],
    [null, "Ghana", "Africa/Accra"],
    [null, "Greece", "Europe/Athens"],
    [null, "Guatemala", "America/Guatemala"],
    [null, "Honduras", "America/Tegucigalpa"],
    [null, "Hungary", "Europe/Budapest"],
    [null, "Iceland", "Atlantic/Reykjavik"],
    [null, "India", "Asia/Kolkata"],
    [null, "Iran", "Asia/Tehran"],
    [null, "Iraq", "Asia/Baghdad"],
    [null, "Ireland", "Europe/Dublin"],
    [null, "Israel", "Asia/Jerusalem"],
    [null, "Italy", "Europe/Rome"],
    [null, "Jamaica", "America/Jamaica"],
    [null, "Japan", "Asia/Tokyo"],
    [null, "Jordan", "Asia/Amman"],
    [null, "Kenya", "Africa/Nairobi"],
    [null, "Kosovo", "Europe/Belgrade"],
    [null, "Kuwait", "Asia/Kuwait"],
    [null, "Malaysia", "Asia/Kuala_Lumpur"],
    [null, "Morocco", "Africa/Casablanca"],
    [null, "Myanmar", "Asia/Yangon"],
    [null, "Nepal", "Asia/Kathmandu"],
    [null, "Netherlands", "Europe/Amsterdam"],
    [null, "New Zealand", "Pacific/Auckland"],
    [null, "Nicaragua", "America/Managua"],
    [null, "Nigeria", "Africa/Lagos"],
    [null, "Norway", "Europe/Oslo"],
    [null, "Pakistan", "Asia/Karachi"],
    [null, "Paraguay", "America/Asuncion"],
    [null, "Peru", "America/Lima"],
    [null, "Philippines", "Asia/Manila"],
    [null, "Poland", "Europe/Warsaw"],
    [null, "Portugal", "Europe/Lisbon"],
    [null, "Puerto Rico", "America/Argentina/San_Juan"],
    [null, "Qatar", "Asia/Qatar"],
    [null, "Romania", "Europe/Bucharest"],
    [null, "Rwanda", "Africa/Kigali"],
    [null, "Saudi Arabia", "Asia/Riyadh"],
    [null, "Serbia", "Europe/Belgrade"],
    [null, "Singapore", "Asia/Singapore"],
    [null, "South Korea", "Asia/Seoul"],
    [null, "Spain", "Europe/Madrid"],
    [null, "Sudan", "Africa/Khartoum"],
    [null, "Sweden", "Europe/Stockholm"],
    [null, "Switzerland", "Europe/Zurich"],
    [null, "Taiwan", "Asia/Taipei"],
    [null, "Tanzania", "Africa/Dar_es_Salaam"],
    [null, "Thailand", "Asia/Bangkok"],
    [null, "Turkey", "Europe/Istanbul"],
    [null, "Uganda", "Africa/Dar_es_Salaam"],
    [null, "Ukraine", "Europe/Kiev"],
    [null, "United Arab Emirates", "Asia/Dubai"],
    [null, "United Kingdom", "Europe/London"],
    [null, "Uruguay", "America/Montevideo"],
    [null, "Uzbekistan", "Asia/Tashkent"],
    [null, "Venezuela", "America/Caracas"],
    [null, "Vietnam", "Asia/Ho_Chi_Minh"],
    [null, "Zimbabwe", "Africa/Harare"],
    [null, "Hong Kong", "Asia/Hong_Kong"],
    [null, "Lebanon", "Asia/Beirut"],

    ["Adelaide", "Australia", "Australia/Adelaide"],
    ["Almaty", "Kazakstan", "Asia/Almaty"],
    ["Anchorage", "USA", "America/Anchorage"],
    ["Atlanta", "USA", "America/New_York"],
    ["Boston", "USA", "America/New_York"],
    ["Brasilia", "Brazil", "America/Sao_Paulo"],
    ["Brisbane", "Australia", "Australia/Brisbane"],
    ["Calgary", "Canada", "America/Edmonton"],
    ["Canberra", "Australia", "Australia/Sydney"],
    ["Cape Town", "South Africa", "Africa/Johannesburg"],
    ["Chicago", "USA", "America/Chicago"],
    ["Dallas", "USA", "America/Winnipeg"],
    ["Darwin", "Australia", "Australia/Darwin"],
    ["Denver", "USA", "America/Denver"],
    ["Detroit", "USA", "America/Detroit"],
    ["Edmonton", "Canada", "America/Edmonton"],
    ["Halifax", "Canada", "America/Halifax"],
    ["Havana", "Cuba", "America/Havana"],
    ["Honolulu", "USA", "Pacific/Honolulu"],
    ["Houston", "USA", "America/Chicago"],
    ["Indianapolis", "USA", "America/Indiana/Indianapolis"],
    ["Jakarta", "Indonesia", "Asia/Jakarta"],
    ["Johannesburg", "South Africa", "Africa/Johannesburg"],
    ["Kiritimati", "Kiribati", "Pacific/Kiritimati"],
    ["Las Vegas", "USA", "America/Los_Angeles"],
    ["Los Angeles", "USA", "America/Los_Angeles"],
    ["Manaus", "Brazil", "America/Manaus"],
    ["Melbourne", "Australia", "Australia/Melbourne"],
    ["Mexico City", "Mexico", "America/Mexico_City"],
    ["Miami", "USA", "America/New_York"],
    ["Minneapolis", "USA", "America/Chicago"],
    ["Montréal", "Canada", "America/Toronto"],
    ["Moscow", "Russia", "Europe/Moscow"],
    ["New Orleans", "USA", "America/Chicago"],
    ["New York", "USA", "America/New_York"],
    ["Novosibirsk", "Russia", "Asia/Novosibirsk"],
    ["Ottawa", "Canada", "America/Toronto"],
    ["Perth", "Australia", "Australia/Perth"],
    ["Philadelphia", "USA", "America/New_York"],
    ["Phoenix", "USA", "America/Phoenix"],
    ["Rio de Janeiro", "Brazil", "America/Sao_Paulo"],
    ["Saint Petersburg", "Russia", "Europe/Moscow"],
    ["Salt Lake City", "USA", "America/Denver"],
    ["San Francisco", "USA", "America/Los_Angeles"],
    ["Seattle", "USA", "America/Los_Angeles"],
    ["St. John's", "Canada", "America/St_Johns"],
    ["Sydney", "Australia", "Australia/Sydney"],
    ["São Paulo", "Brazil", "America/Sao_Paulo"],
    ["Toronto", "Canada", "America/Toronto"],
    ["Vancouver", "Canada", "America/Vancouver"],
    ["Vladivostok", "Russia", "Asia/Vladivostok"],
    ["Washington DC", "USA", "America/New_York"],
    ["Winnipeg", "Canada", "America/Winnipeg"]
];
